#!/bin/bash

if [ "$#" -ne 4 ]; then
  echo "Usage: ./encrypt <plainTextPassword> <keystoreFilePath> <keystoreFilePassword> <certificateAlias>"
  exit 1
fi

java -cp "lib/*" org.wso2.carbon.custom.util.CustomCryptoUtil $1 $2 $3 $4
